// API
export const SET_CONNECTION = 'SET_CONNECTION';
export const STATUS_RUNNING = 'STATUS_RUNNING';
export const SET_STATUS = 'SET_STATUS';
export const SET_TOPICS = 'SET_TOPICS';
export const SET_SCHEMA = 'SET_SCHEMA';
export const SET_DB_INFO = 'SET_DB_INFO';
export const SET_OUTPUT_TABLE = 'SET_OUTPUT_TABLE';
export const SET_QUERY_EXECUTING = 'SET_QUERY_EXECUTING';
export const SET_QUERY_EXECUTED = 'SET_QUERY_EXECUTED';
export const SET_QUERY_TERMINATING = 'SET_QUERY_TERMINATING';
export const SET_QUERY_TERMINATED = 'SET_QUERY_TERMINATED';
export const LOAD_ERROR = 'LOAD_ERROR';
export const QUERY_ERROR = 'QUERY_ERROR';
export const SET_DATABASE = 'SET_DATABASE';
export const SET_DATA = 'SET_DATA';
export const DATA_LOADING = 'DATA_LOADING';
export const DATA_ERROR = 'DATA_ERROR';

// UI
export const QUERY_EXECUTING = 'QUERY_EXECUTING';
export const QUERY_TERMINATING = 'QUERY_TERMINATING';
export const SET_CODE = 'SET_CODE';
export const CLOSE_DESCRIPTION = 'CLOSE_DESCRIPTION';
export const TOPIC_DELETING = 'TOPIC_DELETING';
export const TOPIC_DELETED = 'TOPIC_DELETED';
export const DELETE_ERROR = 'DELETE_ERROR';
export const SET_KEEP_TABLE = 'SET_KEEP_TABLE';
export const APPEND_MESSAGE = 'APPEND_MESSAGE';

// Producer
export const PRODUCERS_LOADED = 'PRODUCERS_LOADED';
export const PRODUCER_ERROR = 'PRODUCER_ERROR';