// API
export const SET_CONNECTION = 'SET_CONNECTION';
export const SET_STATUS = 'SET_STATUS';
export const SET_TOPICS = 'SET_TOPICS';
export const SET_SCHEMA = 'SET_SCHEMA';
export const SET_DB_INFO = 'SET_DB_INFO';
export const SET_OUTPUT_TABLE_UPDATED = 'SET_OUTPUT_TABLE_UPDATED';
export const SET_QUERY_EXECUTING = 'SET_QUERY_EXECUTING';
export const SET_QUERY_EXECUTED = 'SET_QUERY_EXECUTED';
export const SET_QUERY_TERMINATING = 'SET_QUERY_TERMINATING';
export const SET_QUERY_TERMINATED = 'SET_QUERY_TERMINATED';
export const LOAD_ERROR = 'LOAD_ERROR';

// UI
export const QUERY_EXECUTING = 'QUERY_EXECUTING';
export const QUERY_TERMINATING = 'QUERY_TERMINATING';
export const SET_CODE = 'SET_CODE';
export const CLOSE_DESCRIPTION = 'CLOSE_DESCRIPTION';