title: Burroughs
description: Test

remote_theme: rundocs/jekyll-rtd-theme

repository: akaczano/BurroughsPrototype

exclude:
  - README.md

baseurl: /Burroughs/Burroughs

plugins:
  # Necessary to use the ReadTheDocs theme
  - jekyll-remote-theme
  # Added by GitHub pages by default. Should have no effect on deployment, but
  # allows for local building.
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
